### ISSUE TITLE
Prioritize products with matching tags in the advanced search result

### ISSUE THREAD

**Issue by lat9** [lat9/ZenTags#4]
Update the plugin's search additions to give _priority_ to products whose defined tags match the requested keywords.

**Comment by lat9** [comment]
Noting that I've chosen to not include this feature in the initial release.

**Comment by lankeeyankee** [comment]
Would love it if you ever add this!

**Comment by lat9** [comment]
Yep, it's on "the list" ... just a tad complicated.
